### ISSUE TITLE
Quick Edit - Hidden inptut "date_creation_time" cut-off seconds

### ISSUE THREAD

**Issue by ondrejkrhut** [Piwigo/AdminTools#12]
When using Quick edit on a photo and save the picture it cut-off seconds from the time of the picture.
Hidden inptut "date_creation_time" contains value only with hours and minutes.
Please add seconds to the value too.

**Comment by ondrejkrhut** [comment]
I have already created a pull request to fix this.

**Comment by plegall** [comment]
Fixed in https://github.com/Piwigo/AdminTools/commit/7ba2c3a3af16b4186fa3fb0556ce7e27d77a48ea
