### ISSUE TITLE
Privacy level not showing in picture page

### ISSUE THREAD

**Issue by daniele-athome** [Piwigo/AdminTools#5]
I noticed that when enabling AdminTools, the "Who can see this photo?" information is no longer visible to admin users.
I figured it might be this line: https://github.com/Piwigo/AdminTools/blob/master/include/events.inc.php#L63

But why hide it? I can't find it anywhere else unless I open the quick edit dialog (but it's two clicks away).

Thanks for this wonderful piece of software!

**Comment by plegall** [comment]
Plugin Admin Tools does the same for the "set as representative" button : it moves all admin actions into a single place. That's what the plugin was designed for :-)

**Comment by mistic100** [comment]
Hello,

 - I never understood why this setting was the only one configurable from front-office in Piwigo core.
 - It makes no sense to have the "quick edit" feature be leaves other editable fields scattered in the page

**Comment by daniele-athome** [comment]
I'm ok with grouping all admin actions in a single place, but I'm talking about the information text here, the one showed in the right section of the picture page (along with file name, file size, tags, etc.).

**Comment by daniele-athome** [comment]
Oh my, it's editable. Sorry I never realized it :-)
What about just showing it and remove the anchor?

**Comment by plegall** [comment]
Having such "read only info" on gallery side doesn't sound really useful to me.

Tip (if you have keyboard), on the page of the photo, if AdminTools is activated, type ctrl+e and you'll see the current privacy level :-)

**Comment by daniele-athome** [comment]
"May the fork be with me" :-)
Thanks again!

**Comment by daniele-athome** [comment]
If you'll ever be interested:
https://github.com/daniele-athome/AdminTools/commit/8bf2f0b2069a5cd1b6f512bca4e4b5863655be27

:-)
